---
apiVersion: skaffold/v1beta5
kind: Config
build:
  artifacts:
  - image: frontend
    context: src/frontend
  - image: api
    context: src/api
  - image: helloworldservice
    context: src/helloworldservice
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
profiles:
- name: travis-ci
  build:
    local:
      push: false
