apiVersion: v1
kind: Service
metadata:
  name: helloworldservice
  labels:
    app: helloworldservice
spec:
  type: ClusterIP
  selector:
    app: helloworldservice
  ports:
    - name: grpc-web-port
      port: 1234
      targetPort: 9090
