---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
spec:
  template:
    metadata:
      labels:
        app: auth
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: auth
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            tcpSocket:
              port: 8080
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            tcpSocket:
              port: 8080
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          env:
            - name: AUTH_FLASK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: auth_flask_secret_key
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: auth0_client_id
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: auth0_client_secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: http
      port: 1234
      targetPort: 8080
