# ---
# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: auth
# spec:
#   template:
#     metadata:
#       labels:
#         app: auth
#     spec:
#       terminationGracePeriodSeconds: 5
#       containers:
#         - name: server
#           image: auth
#           ports:
#             - containerPort: 8080
#           readinessProbe:
#             initialDelaySeconds: 5
#             periodSeconds: 10
#             tcpSocket:
#               port: 8080
#           livenessProbe:
#             initialDelaySeconds: 15
#             periodSeconds: 20
#             tcpSocket:
#               port: 8080
#           resources:
#             requests:
#               cpu: 100m
#               memory: 64Mi
#             limits:
#               cpu: 200m
#               memory: 128Mi
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: auth
# spec:
#   type: ClusterIP
#   selector:
#     app: auth
#   ports:
#     - name: http
#       port: 1234
#       targetPort: 8080
# ----
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: auth
# spec:
#   gateways:
#   - gateway
#   hosts:
#   - "*"
#   http:
#   - match:
#     - uri:
#         exact: /login
#     - uri:
#         exact: /callback
#     - uri:
#         exact: /logout
#     route:
#     - destination:
#         host: auth
#         port:
#           number: 1234
