# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='echo.proto',
  package='main',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12your_service.proto\x12\x04main\x1a\x1cgoogle/api/annotations.proto\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t2\\\n\x0bYourService\x12M\n\x04\x45\x63ho\x12\x13.main.StringMessage\x1a\x13.main.StringMessage\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x10/v1/example/echo:\x01*b\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_STRINGMESSAGE = _descriptor.Descriptor(
  name='StringMessage',
  full_name='main.StringMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='main.StringMessage.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['StringMessage'] = _STRINGMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StringMessage = _reflection.GeneratedProtocolMessageType('StringMessage', (_message.Message,), dict(
  DESCRIPTOR = _STRINGMESSAGE,
  __module__ = 'your_service_pb2'
  # @@protoc_insertion_point(class_scope:main.StringMessage)
  ))
_sym_db.RegisterMessage(StringMessage)



_YOURSERVICE = _descriptor.ServiceDescriptor(
  name='YourService',
  full_name='main.YourService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=90,
  serialized_end=182,
  methods=[
  _descriptor.MethodDescriptor(
    name='Echo',
    full_name='main.YourService.Echo',
    index=0,
    containing_service=None,
    input_type=_STRINGMESSAGE,
    output_type=_STRINGMESSAGE,
    serialized_options=_b('\202\323\344\223\002\025\"\020/v1/example/echo:\001*'),
  ),
])
_sym_db.RegisterServiceDescriptor(_YOURSERVICE)

DESCRIPTOR.services_by_name['YourService'] = _YOURSERVICE

# @@protoc_insertion_point(module_scope)
