# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import your_service_pb2 as your__service__pb2


class YourServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Echo = channel.unary_unary(
        '/main.YourService/Echo',
        request_serializer=your__service__pb2.StringMessage.SerializeToString,
        response_deserializer=your__service__pb2.StringMessage.FromString,
        )


class YourServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Echo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_YourServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Echo': grpc.unary_unary_rpc_method_handler(
          servicer.Echo,
          request_deserializer=your__service__pb2.StringMessage.FromString,
          response_serializer=your__service__pb2.StringMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'main.YourService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
